/*
 * Eduardo Wass Rosado
 * eduwass@gmail.com
 */

package edu.ub.prog2.WassRosadoEduardo.vista;

// UI
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

// Control
import edu.ub.prog2.WassRosadoEduardo.controlador.CtrlReproductor;

/**
 *
 * @author ewass
 */
public class ReproductorUB4 extends javax.swing.JFrame {
    
    // Enlace a Controlador
    private CtrlReproductor Controlador;
    
    
    /**
     * Funcion constructora
     */
    public ReproductorUB4() {
        initComponents();
        
        // Establecer el look and feel de Windows
        try {
            //Set the required look and feel
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //Update the component tree - associate the look and feel with the given frame.
            SwingUtilities.updateComponentTreeUI(this);
        }//end try
        catch (Exception ex) {
            ex.printStackTrace();
        }//end catch

        // Centrar ventana
        this.setLocationRelativeTo(null);
        
        // Inicializar control
        this.Controlador = new CtrlReproductor();
    }

    /**
     * Retorna el controlador
     * @return 
     */
    public CtrlReproductor DonaControlador(){
        return this.Controlador;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        tabBiblioteca = new javax.swing.JPanel();
        toolbarBiblioteca = new javax.swing.JToolBar();
        btnAddBiblioteca = new javax.swing.JButton();
        btnDelBiblioteca = new javax.swing.JButton();
        btnPLayBiblioteca = new javax.swing.JButton();
        panelBiblioteca = new javax.swing.JPanel();
        bibliotecaScrollPane = new javax.swing.JScrollPane();
        bibliotecaLista = new javax.swing.JList();
        tabListas = new javax.swing.JPanel();
        toolbarListas = new javax.swing.JToolBar();
        btnAddLista = new javax.swing.JButton();
        btnDelLista = new javax.swing.JButton();
        btnPlayLista = new javax.swing.JButton();
        panelListas = new javax.swing.JPanel();
        listasScrollPane = new javax.swing.JScrollPane();
        listasLista = new javax.swing.JList();
        listasCombo = new javax.swing.JComboBox();
        toolbarListas2 = new javax.swing.JToolBar();
        btnAddCancion = new javax.swing.JButton();
        btnDelCancion = new javax.swing.JButton();
        btnPlayCancion = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        btnPlay = new javax.swing.JMenu();
        btnPause = new javax.swing.JMenu();
        btnStop = new javax.swing.JMenu();
        btnNext = new javax.swing.JMenu();
        btnRandom = new javax.swing.JMenu();
        btnRepeat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UB MP3 Player");
        setForeground(java.awt.Color.white);
        setResizable(false);

        tabs.setToolTipText("");

        toolbarBiblioteca.setFloatable(false);
        toolbarBiblioteca.setRollover(true);
        toolbarBiblioteca.setBorderPainted(false);
        toolbarBiblioteca.setFocusable(false);

        btnAddBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnAddBiblioteca.setText("Añadir canción");
        btnAddBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBibliotecaActionPerformed(evt);
            }
        });
        toolbarBiblioteca.add(btnAddBiblioteca);

        btnDelBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnDelBiblioteca.setText("Eliminar canción");
        btnDelBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelBibliotecaActionPerformed(evt);
            }
        });
        toolbarBiblioteca.add(btnDelBiblioteca);

        btnPLayBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/control_play_blue.png"))); // NOI18N
        btnPLayBiblioteca.setText("Reproducir Biblioteca");
        btnPLayBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPLayBibliotecaActionPerformed(evt);
            }
        });
        toolbarBiblioteca.add(btnPLayBiblioteca);

        bibliotecaLista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        bibliotecaScrollPane.setViewportView(bibliotecaLista);

        javax.swing.GroupLayout panelBibliotecaLayout = new javax.swing.GroupLayout(panelBiblioteca);
        panelBiblioteca.setLayout(panelBibliotecaLayout);
        panelBibliotecaLayout.setHorizontalGroup(
            panelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBibliotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bibliotecaScrollPane)
                .addContainerGap())
        );
        panelBibliotecaLayout.setVerticalGroup(
            panelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBibliotecaLayout.createSequentialGroup()
                .addComponent(bibliotecaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabBibliotecaLayout = new javax.swing.GroupLayout(tabBiblioteca);
        tabBiblioteca.setLayout(tabBibliotecaLayout);
        tabBibliotecaLayout.setHorizontalGroup(
            tabBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbarBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
            .addComponent(panelBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabBibliotecaLayout.setVerticalGroup(
            tabBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBibliotecaLayout.createSequentialGroup()
                .addComponent(toolbarBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Mi Biblioteca", tabBiblioteca);

        toolbarListas.setFloatable(false);
        toolbarListas.setRollover(true);
        toolbarListas.setBorderPainted(false);
        toolbarListas.setFocusable(false);

        btnAddLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page_blank_add.png"))); // NOI18N
        btnAddLista.setText("Nueva Lista");
        btnAddLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddListaActionPerformed(evt);
            }
        });
        toolbarListas.add(btnAddLista);

        btnDelLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page_blank_close.png"))); // NOI18N
        btnDelLista.setText("Eliminar Lista");
        btnDelLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelListaActionPerformed(evt);
            }
        });
        toolbarListas.add(btnDelLista);

        btnPlayLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/control_play_blue.png"))); // NOI18N
        btnPlayLista.setText("Reproducir Lista");
        btnPlayLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayListaActionPerformed(evt);
            }
        });
        toolbarListas.add(btnPlayLista);

        listasLista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listasScrollPane.setViewportView(listasLista);

        listasCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        toolbarListas2.setFloatable(false);
        toolbarListas2.setBorderPainted(false);
        toolbarListas2.setFocusable(false);

        btnAddCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cd_add.png"))); // NOI18N
        btnAddCancion.setText("Añadir canción");
        btnAddCancion.setFocusable(false);
        btnAddCancion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddCancion.setInheritsPopupMenu(true);
        btnAddCancion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarListas2.add(btnAddCancion);

        btnDelCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cd_delete.png"))); // NOI18N
        btnDelCancion.setText("Quitar canción");
        btnDelCancion.setFocusable(false);
        btnDelCancion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelCancion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarListas2.add(btnDelCancion);

        btnPlayCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/control_play_blue.png"))); // NOI18N
        btnPlayCancion.setText("Reproducir canción");
        btnPlayCancion.setFocusable(false);
        btnPlayCancion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayCancion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarListas2.add(btnPlayCancion);

        javax.swing.GroupLayout panelListasLayout = new javax.swing.GroupLayout(panelListas);
        panelListas.setLayout(panelListasLayout);
        panelListasLayout.setHorizontalGroup(
            panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listasCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listasScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toolbarListas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelListasLayout.setVerticalGroup(
            panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListasLayout.createSequentialGroup()
                .addComponent(listasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listasScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolbarListas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabListasLayout = new javax.swing.GroupLayout(tabListas);
        tabListas.setLayout(tabListasLayout);
        tabListasLayout.setHorizontalGroup(
            tabListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbarListas, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
            .addComponent(panelListas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabListasLayout.setVerticalGroup(
            tabListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabListasLayout.createSequentialGroup()
                .addComponent(toolbarListas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelListas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Listas de Reproducción", tabListas);

        menuPrincipal.setPreferredSize(new java.awt.Dimension(246, 44));

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/control_play_blue.png"))); // NOI18N
        menuPrincipal.add(btnPlay);

        btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/control_pause_blue.png"))); // NOI18N
        menuPrincipal.add(btnPause);

        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/control_stop_blue.png"))); // NOI18N
        menuPrincipal.add(btnStop);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/control_fastforward_blue.png"))); // NOI18N
        menuPrincipal.add(btnNext);

        btnRandom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/control_repeat_blue.png"))); // NOI18N
        menuPrincipal.add(btnRandom);

        btnRepeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow_switch.png"))); // NOI18N
        menuPrincipal.add(btnRepeat);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPLayBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPLayBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPLayBibliotecaActionPerformed

    private void btnDelBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelBibliotecaActionPerformed

    private void btnAddBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBibliotecaActionPerformed
        // TODO add your handling code here:
        FrmAfegirFitxer Ventana = new FrmAfegirFitxer(this, this.Controlador);
        Ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddBibliotecaActionPerformed

    private void btnAddListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddListaActionPerformed

    private void btnDelListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelListaActionPerformed

    private void btnPlayListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReproductorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReproductorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReproductorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReproductorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReproductorUB4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList bibliotecaLista;
    private javax.swing.JScrollPane bibliotecaScrollPane;
    private javax.swing.JButton btnAddBiblioteca;
    private javax.swing.JButton btnAddCancion;
    private javax.swing.JButton btnAddLista;
    private javax.swing.JButton btnDelBiblioteca;
    private javax.swing.JButton btnDelCancion;
    private javax.swing.JButton btnDelLista;
    private javax.swing.JMenu btnNext;
    private javax.swing.JButton btnPLayBiblioteca;
    private javax.swing.JMenu btnPause;
    private javax.swing.JMenu btnPlay;
    private javax.swing.JButton btnPlayCancion;
    private javax.swing.JButton btnPlayLista;
    private javax.swing.JMenu btnRandom;
    private javax.swing.JMenu btnRepeat;
    private javax.swing.JMenu btnStop;
    private javax.swing.JComboBox listasCombo;
    private javax.swing.JList listasLista;
    private javax.swing.JScrollPane listasScrollPane;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JPanel panelBiblioteca;
    private javax.swing.JPanel panelListas;
    private javax.swing.JPanel tabBiblioteca;
    private javax.swing.JPanel tabListas;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JToolBar toolbarBiblioteca;
    private javax.swing.JToolBar toolbarListas;
    private javax.swing.JToolBar toolbarListas2;
    // End of variables declaration//GEN-END:variables
}
